networks:
    system:
        name: system

services:
    mysql:
        image: mysql:8.3
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: root123
        networks:
            system:
                aliases:
                    - mysql

    laravel:
        image: webdevops/php-apache-dev:8.3-alpine
        container_name: laravel
        command: supervisord
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/app
            - ./database/supervisord.conf:/etc/supervisord.conf
        environment:
            WEB_DOCUMENT_ROOT: /app/public
        networks:
            system:
                aliases:
                    - laravel
